### ISSUE TITLE
Non standard header file

### ISSUE THREAD

**Issue by boborbt** [jackperlo/bachelor-thesis#1]
The header file pointed by the following url is not standard and won't compile on non-linux machines. It is also not a good practice to include these files since its only purpose is to replace the inclusion of multiple header files (which might not all be relevant to your project causing unnecessary compilation overhead).

https://github.com/jackperlo/bachelor-thesis/blob/3ededdc5d6679813c2c4f50b58257c23455ee494/src/lib/common.h#L6

Please substituted it with relevant (standard) headers.

**Comment by jackperlo** [comment]
stdc++.h replaced by the related header files of interest
